### ISSUE TITLE
[SPRING] Unit incl. coverage report and UI-Tests with demo app

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/android-cmp-app#110]

**Comment by AAverin** [comment]
To make sure we can create UI tests for the Privacy Manager layer written in html, we should:
- have documentation on how classes and ids are structured in the html
- make sure that either javascript logic is working when triggering expandable elements or that they are working without javascript - Espresso can use XMLPath to find elements in WebViews but most likely will not work with javascript

**Comment by leodoin** [comment]
@AAverin , just to give you an update here: our test  coverage was sharply increased on the last few months and now we are going to prioritise to include the reports on github with each new release. Nevertheless you can aways run the tests on our repo to check the coverage manually.

**Comment by atanurdemirci** [comment]
This is an ongoing Task but not a real issue, we'll continue improving the test coverage. Resolving this!

**Comment by leodoin** [comment]
@AAverin ,  we already implemented this on our anchor tags on our web consent layers and we use them to UI test our example app espresso framework. Now we just have to align to provide some documentation on it, but you can already follow the example app UI tests implementation a a main guide :)
Closing this ticket...
