### ISSUE TITLE
[SPRING] Please make sure to cache the permissions to allow quick app start

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/android-cmp-app#118]
Please cache last vendors, custom vendors, purposes and custom purposes settings plus fallback if none were fetched so far, so we can get the settings for quick start of the app and also in bad network conditions.

**Comment by pkcpkc** [comment]
Offline should work, too!

**Comment by AAverin** [comment]
@leodoin

**Comment by leodoin** [comment]
@AAverin , @pkcpkc , this has been implemented via `public static StoreClient.getUserConsent(SharedPref)`. Can we close this issue or is there still something missing?

**Comment by AAverin** [comment]
@leodoin Can application using SP SDK work offline if user have already given consent at least once? We have some cached values in the app that users can see when they have bad network connections. Users can start the app if they have no connection at all and see cached articles.

**Comment by leodoin** [comment]
> Can application using SP SDK work offline if user have already given consent at least once?

Yes, once theirs a consent stored you can take advantage of the above mentioned method to recover the consents off-line and still show ached adds.

**Comment by leodoin** [comment]
I'll close this issue, but pls feel free to open a new one if you find any integration problems related to off-line/cached mode.
