### ISSUE TITLE
[SPRING] Save and Exit button doesn't work well

### ISSUE THREAD

**Issue by dpliskov** [SourcePointUSA/android-cmp-app#119]
On Options Screen there is a button Save and Exit. 
When i press this button i get the empty vendor and category lists.
Also it looks like this button resets all options to off.

**Comment by andresilveirah** [comment]
@dpliskov thank you for bringing this issue up. We're currently working on it and you'll have a fix soon. I'll keep the issue open and ping you here about it.

**Comment by dpliskov** [comment]
Now there is a button Auswahl speichern & schliessen. 
Looks like it still doesn't work. At least i get nothing in setOnConsentReady callback. And nothing is saved.

**Comment by AAverin** [comment]
could be related to #172

**Comment by leodoin** [comment]
possibly solved already as mentioned here #172 . Should we close it?

**Comment by AAverin** [comment]
I think this can be closed

**Comment by leodoin** [comment]
closing the issue
