### ISSUE TITLE
AuthExample broken

### ISSUE THREAD

**Issue by dkzy** [SourcePointUSA/android-cmp-app#121]
The Authexample is still using Consent Class while it has been removed from cmplibrary already. Hence it is broken now.

**Comment by andresilveirah** [comment]
@dkzy thank you bringing up this issue. I just created a ticket to update the AuthExample app for the newest SDK version and I'll ping you once it's ready.

**Comment by dkzy** [comment]
Thanks

**Comment by leodoin** [comment]
@dkzy can you give our develop branch a try. It has been fixed :)
We'll wait for more QA feedbacks before closing this issue though.

**Comment by dkzy** [comment]
I will . Thanks.

**Comment by leodoin** [comment]
closing this issue as the auth example looks to be working just fine
