### ISSUE TITLE
[SPRING] Is there any way just to get attributes to create consent screen view?

### ISSUE THREAD

**Issue by dpliskov** [SourcePointUSA/android-cmp-app#129]
This issue is connected to issue [https://github.com/SourcePointUSA/android-cmp-app/issues/116](116).

I would like to create a consent screen view myself. I need only get attributes in some callback. But i have to create the view in NativeMessage.init method.

**Comment by leodoin** [comment]
@dpliskov , we have this call back already :)
you just have to override the method `public void setAttributes(NativeMessageAttrs attrs)` like we do here: [https://github.com/SourcePointUSA/android-cmp-app/blob/develop/app/src/main/java/com/sourcepoint/test_project/MainActivity.java] (line 84)

Does this answer your question?

**Comment by dpliskov** [comment]
So, can i just don't set setOnConsentUIReady callback and use my own view?
In this case are there any methods in SDK to do AcceptAll or RejectAll actions?

**Comment by leodoin** [comment]
No, by design you will aways receive have to implement `setOnConsentUIReady `, but using the `setAttributes(NativeMessageAttrs attrs)` you can fully customise the message layout and the `NativeMessageView` will call the right action callback for you. It is also possible to change the buttons behaviour, although  it is not recommended as it leads to huge confusions when setting those actions on the dashboard.

**Comment by leodoin** [comment]
@dpliskov , all methods of NativeMessage class are public, so you can overrride them at will.
For instance, if you want to completely change the behaviour of the onShowOptions() action you can simply override this method: [NativeMessage.java#L54](https://github.com/SourcePointUSA/android-cmp-app/blob/68ddef1012549e19541275b4e1653758512dbba4/cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/NativeMessage.java#L54  )
with something like this:
private NativeMessage buildNativeMessage(){
        return new NativeMessage(this){
            @Override
            public void init(){
                super.init();
                // When using a customized layout one can completely override the init method
                // not calling super.init() and inflating the native view with the chosen layout instead.
                // In this case its important to set all the default child views using the setter methods
                // like its done in the super.init()
            }
            @Override
            public void setAttributes(NativeMessageAttrs attrs){
                super.setAttributes(attrs);
                //Here one can extend this method in order to set customized attributes other then the ones
                //already set in the super.setAttributes. No need to completely override this method.
            }
            @Override
            public void setCallBacks(GDPRConsentLib consentLib) {
                setOnclickAction(getAcceptAll(), consentLib);
                setOnclickAction(getRejectAll(), consentLib);
                setOnclickAction(getCancel(), consentLib);

                //some code that calls
                customOnClickAction(getShowOptions(), consentLib);
            }
        };
}

**Comment by dpliskov** [comment]
I set my own onClickListener after setAttributes method. It works fine.
