### ISSUE TITLE
`ConsentLibException.BuildException` is not used in code

### ISSUE THREAD

**Issue by AAverin** [SourcePointUSA/android-cmp-app#187]
ConsentLibBuilder claims to validate data and throw `ConsentLibException.BuildException`, but looks like that class is only used in the comments and never actually thrown

**Comment by leodoin** [comment]
@AAverin , sorry for the delay here. This issue has been forgotten on the backlog pile as it is not a top priority one. Nevertheless it's gonna be included on our next sprint, so buckle up for new updates coming soon!

**Comment by leodoin** [comment]
@AAverin this has been solved on our latest release: https://github.com/SourcePointUSA/android-cmp-app/releases/tag/5.3.8 
Closing the issue...
