### ISSUE TITLE
Signature of the method customConsentTo

### ISSUE THREAD

**Issue by dpliskov** [SourcePointUSA/android-cmp-app#207]
Parameters of method customConsentTo have type ArrayList. But it is too specific. Could be just List or Collection.

**Comment by hameno** [comment]
Yes, please change this to follow general best practices for Java

**Comment by hameno** [comment]
I just saw 5.3.3 that fixes this. Could you please reference the issues in the future when doing changes? This will automatically update the liked tickets and provides more visibility.
