### ISSUE TITLE
SDK leaks webview instances

### ISSUE THREAD

**Issue by hameno** [SourcePointUSA/android-cmp-app#219]
After showing the privacy manager with `it.showPm()`and then closing via the button in the UI, the webview stays attached to the context (in detached state):
![image](https://user-images.githubusercontent.com/365084/88531272-dcbb5d00-d002-11ea-9449-a79cb98ae589.png)
Looking at the source code I cannot find any calls to https://developer.android.com/reference/android/webkit/WebView?hl=en#destroy()

**Comment by leodoin** [comment]
Thanks for bringing this up @hameno . Could you also pls confirm on with version of the SDK are you seeing this issue?

**Comment by hameno** [comment]
5.3.1

**Comment by hameno** [comment]
I just saw 5.3.3 that fixes this. Could you please reference the issues in the future when doing changes? This will automatically update the liked tickets and provides more visibility.

**Comment by hameno** [comment]
Confirm fixed in 5.3.3
