### ISSUE TITLE
[SPRING] Network exceptions

### ISSUE THREAD

**Issue by dpliskov** [SourcePointUSA/android-cmp-app#235]
**Describe the bug**
Different exception structure in case of missing internet.

**About your campaign (please complete the following information):**
 - Account Id = 75
 - Property Id = 4600
 - Property Name = WELT-NEWS-ANDROID
 - Campaign Env = 134094
 - Targeting Params (if any)
 - AuthId (if any)

**About your environment**
 - SDK version = 5.3.3
 - Device: = Samsung Galaxy S10
 - OS: Android 9

**To Reproduce**

1. Disable Internet 
2. Try to open native consent layer screen
3. The exception is **ConsentLibException with cause ConsentLibException$NoInternetConnectionException**
<br/>
      
1. Enable Internet 
2. Open native consent layer screen.
3. Disable Internet
4. Press the button Zustimmen 
5. The exception is **ConsentLibException$NoInternetConnectionException**

**Expected behavior**
It's not critical, but would be better to have one standard structure of exceptions in similar error cases.

**Comment by leodoin** [comment]
Thanks for the feedback here @dpliskov .This is indeed a behaviour that we should change and we are including this to our next sprint already. So bucle up and keep tuned!

**Comment by leodoin** [comment]
@dpliskov , could you pls give https://github.com/SourcePointUSA/android-cmp-app/releases/tag/5.3.8 a try? :)

**Comment by leodoin** [comment]
We have run our QA extensively on that and it looks good. So I'm closing the issue, but pls let us now if you still find any unexpected behaviour.
