### ISSUE TITLE
[SPRING] Privacy Manager webview is delivered without content

### ISSUE THREAD

**Issue by AAverin** [SourcePointUSA/android-cmp-app#238]
**Describe the bug**
Once in a while, at random, I get a Privacy Manager screen that seems to only have first title and paragraph without any switches. Element is not scrollable. There are buttons available. See screenshot attached.

![Screenshot_20200814-163116](https://user-images.githubusercontent.com/1481332/90261629-88f7a300-de4d-11ea-8c61-1c26c20a20ba.jpg)

**About your campaign (please complete the following information):**
 - Account Id 75 
 - Property Id 4600
 - Property Name WELT-NEWS-ANDROID
 - Campaign Env
 - Targeting Params (if any)
 - AuthId (if any)

** About your environment **
 - SDK version 5.3.4
 - Device: [e.g. iPhone6] Oneplus 7t Pro
 - OS: [e.g. iOS8.1] Android 9

**To Reproduce**
Launch the app and select "Einstellungen" to see privacy manager

**Expected behavior**
Expected to see a fully functional privacy manager webview or error delivered

**Screenshots**

**Additional context**
In Logcat I see following message that could be related
```
Access to fetch at 'https://cdn.privacy-mgmt.com/consent/tcfv2/privacy-manager/privacy-manager-view?siteId=4600&vendorListId=5e704d82b8e05c5a7d171c7b&consentLanguage=DE' from origin 'https://notice.sp-prod.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.", source: https://notice.sp-prod.net/privacy-manager/index.html?site_id=4600&message_id=134094&consentUUID=f02d78ae-f185-471f-9c4c-209bb0840049 (0)
```

**Comment by atanurdemirci** [comment]
This issue appeared due to a infrastructure issue in our backend, resolving!
