### ISSUE TITLE
[SRPING] User consent is not properly updated by privacy manager

### ISSUE THREAD

**Issue by AAverin** [SourcePointUSA/android-cmp-app#244]
**Describe the bug**
Test case:
user starts the app, presses “Settings” and then “Save settings”, giving no consent
user opens an article, clicks on the embed and sees the dialog “Please enable social consent vendors”
user enabled social consent vendors, data is correctly updated on Android 5.3.6, user sees social embeds
user goes to Privacy Manager and switches off Social Networks
user goes back to the article and still sees social embeds enabled, data in the log states that vendorGrants still are set to true for social vendors (which is wrong)

**About your campaign (please complete the following information):**
```
const val ACCOUNT_ID = 75
const val PROPERTY = "WELT-NEWS-ANDROID"
const val PROPERTY_ID = 4600
const val PM_ID = "134094"
```

** About your environment **
 - SDK version 5.3.6

**To Reproduce**
See test case above

**Expected behavior**
Privacy manager should correctly update `vendorGrants` values

**Additional context**
Here is what I see from my debugging.
User doesn’t give any consent => we get vendorGrants with false values
We save user social consent => we get vendorGrants with true values
User goes out of the article back to the main screen => We get on onConsentReady called with userConsent, again with true values
User goes to settings and opens privacy manager, disables social networks => we get vendorGrants with false values
User goes back to main screen => we get onConsentReady with vendorGrants true  values (! THIS IS A BUG !)

**Comment by leodoin** [comment]
>user opens an article, clicks on the embed and sees the dialog “Please enable social consent vendors”

@AAverin , could you pls describe what this action means from the SDK API perspective? Specifically with which parameters is the customConsentTo method being called?

**Comment by AAverin** [comment]
@leodoin the dialog is displayed by our app, it has a single action that allows to 'enable all social vendors`.
We build a list of all social vendors using this algorithm:
```
Pseudo-algorithm:

1. Fetch vendor to purpose mapping for your property: https://sourcepoint.mgr.consensu.org/tcfv2/vendor-list/vendor-purpose-mapping/?siteId=${YOUR_PROPERTY_ID}
2. Filter out only those vendors that contain your property-specific purposeId of "Soziale Netzwerke". This purpose serves as an oembed-marker.
3. Collect all the purposes of the filtered vendors in two separate sets to eliminate duplicates – consent purposes and legitimate interest purposes.
4. Use the SP SDK method to enable all filtered vendors and unique purposes on user button click.
```

```
fun writeConsentData(): Completable {
        return sourcePointService.getVendorPurposeMapping()
                .map {
                    val vendors = mutableSetOf<String>()
                    val categories = mutableSetOf<String>()
                    val legIntCategories = mutableSetOf<String>()

                    it.filter { vendor ->
                                vendor.categories.any { it._id == SOCIAL_PURPOSE_ID }
                            }
                      .forEach {vendor ->
                                vendors.add(vendor.vendorId)
                                vendor.categories.forEach {
                                    if (it.type == LEGITIMATE_INTEREST) {
                                        legIntCategories.add(it._id)
                                    } else {
                                        categories.add(it._id)
                                    }
                                }
                            }
                    CustomConsent(vendors, categories, legIntCategories)
                }
                .observeOn(rxSchedulers.mainThread)
                .flatMapCompletable { customConsent ->
                    Completable.create { emitter ->
                        val lib = GDPRConsentLib.newBuilder(ACCOUNT_ID, PROPERTY, PROPERTY_ID, PM_ID, baseContext)
                                .setOnConsentReady {
                                    consentDataLocalRepository.store(it)
                                    emitter.onComplete()
                                }
                                .setOnError {
                                    emitter.onError(it)
                                }
                                .build()

                        // Have to wrap parameters into ArrayList, because of the method signature ... 😱
                        // I've informed cmp developers about it (https://github.com/SourcePointUSA/android-cmp-app/issues/207)
                        lib.customConsentTo(ArrayList(customConsent.vendors), ArrayList(customConsent.categories), ArrayList(customConsent.legIntCategories))

                    }
                }

    }

```

**Comment by atanurdemirci** [comment]
We haven't been able to reproduce this in our screensharing session, resolving for now.
