### ISSUE TITLE
onError called twice in some cases

### ISSUE THREAD

**Issue by anasonline** [SourcePointUSA/android-cmp-app#246]
**Describe the bug**
While working on our error handling logic we noticed that the SDK returns 2 consecutive error callbacks if the request to `notice.sp-prod.net` was unsuccessful. In that case, the ConsentLibException object returns 2 error messages that look like:

The first error callback: `Error due to android API: net::ERR_SPDY_PROTOCOL_ERROR`
The second error callback: `Error due to android API: il@a98d297
`
We also have the same issue when the Privacy Manager request fails. Since we depend on the SDKs error callback to show error messages to the user, it means that the error dialog gets shown twice. The SDK should return only one error callback per error. 

**About your campaign (please complete the following information):**
 - Account Id: 75
 - Property Id: 5594
 - Property Name: BILD-NEWS-ANDROID

** About your environment **
 - SDK version: 5.3.6
 - Device: Google Pixel 3a
 - OS: Android 10

**To Reproduce**

1. Use Charles proxy or a similar application to block calls to `notice.sp-prod.net`
2. Install and start the app for the first time 
3. You get two error callbacks and two errors registered to our logs
4. Open the main menu and click on "Datenschutz" (privacy) item.
5. Click on the "Privacy Settings" button to request the privacy manager
6. You get two error callbacks, and the user sees two error dialogs on the interface

**Expected behavior**
The SDK should return only one error callback per error.

**Comment by andresilveirah** [comment]
@anasonline we were able to identify this issue on our end and we should be able to have a fix this week still.

**Comment by leodoin** [comment]
@anasonline , could you pls give https://github.com/SourcePointUSA/android-cmp-app/releases/tag/5.3.8 a try? :)

**Comment by anasonline** [comment]
@leodoin I confirm that the issue has been fixed in the new update, thank you :)

**Comment by leodoin** [comment]
nice! closing the issue 😄
