### ISSUE TITLE
Incorrect callback behaviour when "sourcepoint.mgr.consensu.org" request fails

### ISSUE THREAD

**Issue by anasonline** [SourcePointUSA/android-cmp-app#257]
**Describe the bug**
If the call to `sourcepoint.mgr.consensu.org` fails (e.g. connection drops or 403 server error) the SDK returns the following callback chain:

`OnConsentUIReady -> OnConsentUIFinished -> OnError`

As a result of that, when the app is installed for the first time, the consent layer appears for a second before it gets immediately dismissed. As it's clear, the OnError callback comes too late in that case. 

**About your campaign:**
- Account Id: 75
- Property Id: 5594
- Property Name: BILD-NEWS-ANDROID

** About your environment **

- SDK version: 5.3.7
- Device: Google Pixel 3a
- OS: Android 10

**To Reproduce**
1. Block or emulate an error response for the request to: `sourcepoint.mgr.consensu.org`
2. Install and launch the app
3. The user will see the consent layer appears and disappears quickly

**Expected behavior**
The SDK should return an `onError` callback which we can use to handle this error case on the client-side. The consent layer should not be displayed at all in that case.

**Comment by pkcpkc** [comment]
Acknowledged - no feedback yet.

**Comment by haerju** [comment]
@anasonline We received the following feedback from our engineering team on this isseu.  _This took a while to understand properly and make the right decision but, from our current use-cases this should be impossible.  Our messages are preloaded in the wrapper API so there should be NO API calls when the message is being loaded that could cause this error

Could we possibly look into whether this is still an issue?_

Do you mind checking if this issue stillo ccurs?

**Comment by anasonline** [comment]
@haerju Thanks for your answer. We are actually manually calling `https://sourcepoint.mgr.consensu.org/tcfv2/vendor-list/vendor-purpose-mapping/` to get vendor categories since the purposeGrants object doesn't provide information on purpose type through the SDK methods. I guess once the SDK provides us with a native way to do that then we shouldn't have such an issue anymore. I would say that this ticket can be closed with the hope that you provide us soon with an SDK method that could provide us a way to get the vendor categories without a need for the manual request.

**Comment by haerju** [comment]
@anasonline Thank you for your feedback. We currently have no plans of making this API natively but we have a standardized feature request process in place. If you connect with Selim at Spring he will be able to make sure this accurately relfected in terms of priority.

**Comment by haerju** [comment]
@andresilveirah Can you please close this ticket and archive?
