### ISSUE TITLE
NativeMessage is leaking 

### ISSUE THREAD

**Issue by AAverin** [SourcePointUSA/android-cmp-app#271]
**Describe the bug**
There are many instances of NativeMessage kept in memory

**About your campaign (please complete the following information):**
Reproduced in the sample app

** About your environment **
Sample app

**To Reproduce**
See the code in PR https://github.com/SourcePointUSA/android-cmp-app/pull/270

1. Open the app and see native message
2. Press on the + in toolbar to visit another activity
3. Press back to go back, see native message
4. Repeat steps 2-3 a few times
5. Run Profiler in Android Studio and select Memory
6. Do a few GCs to make sure stale memory is cleared
7. Dump memory and find CustomNativeMessage
8. Observe many instances still alive

![image](https://user-images.githubusercontent.com/1481332/94274273-c750a980-ff45-11ea-957c-49c08f2ec637.png)

**Expected behavior**
There shouldn't be many instances of custom native messages kept in memory

**Screenshots**

**Additional context**
Having another activity to visit, every new instance of native message seems to be kept in memory

**Comment by leodoin** [comment]
@AAverin , thanks a lot for assembling sample code!
Fortunately this leak can be avoided on the application level (no need for a SDK release) by passing the applicationContext to the view instead of the activity itself:
```Java
    private NativeMessage buildNativeMessage() {
        return new CustomNativeMessage(getApplicationContext());
    }
```

**Comment by leodoin** [comment]
Basically the garbage  collector cannot get rid of the instances of `CustomNativeMessage` as they keep a reference to the `MainActivity`. @AAverin , could you give it a try on your side?

**Comment by leodoin** [comment]
@AAverin , @drabinowitz , any updates here ?

**Comment by AAverin** [comment]
@leodoin I have asked @pliskov to take a look.

**Comment by leodoin** [comment]
Closing the issue as it does not seem to the related to the SDK codebase, but rather to it's implementation. Pls feel free to reopen it if you happen to conclude otherwise.

**Comment by pkliang** [comment]
> @AAverin , thanks a lot for assembling this sample code!
> Fortunately this leak can be avoided on the application level (no need for a SDK release) by passing the `applicationContext` to the view instead of the `MainActivity` itself:
> 
> ```java
>     private NativeMessage buildNativeMessage() {
>         return new CustomNativeMessage(getApplicationContext());
>     }
> ```

Hi @leodoin , I applied the fix as you described above, but still see multiple instances of CustomNativeMessage.

<img width="1549" alt="Screenshot 2020-10-05 at 17 01 44" src="https://user-images.githubusercontent.com/2564841/95096487-9da93680-072c-11eb-8061-cb569438a04a.png">

**Comment by andresilveirah** [comment]
@pkliang thank you for giving it a try and reporting it back to us. We'll try to reproduce that on our Example app and get back to you.

**Comment by AAverin** [comment]
Closing the ticket with a general advice to provide examples on how native layer should be properly integrated to avoid unnecessary memory usage.
