### ISSUE TITLE
[SPRING] "Alle akzeptieren" does NOT enable all vendors BILD iOS and Android

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/android-cmp-app#274]
Clicking 'Alle akzeptieren' in ConsentLayer (or in PM) does not accept everything.
When you open the privacy manager, there are still opted-out categories in the legitimate interest section.

s2r

- start cmp app for the first time
- tab 'Alle akzeptieren'
- open menu
- tab 'Privatssphäreeinstellungen'
- open legitimate interest section

IS:
button called 'Alle akzeptieren' does not opt-in everything

SHOULD
a button called 'Alle akzeptieren' should opt-in everything

**Comment by pkcpkc** [comment]
additional information:
when tabbing Einstellungen oder ablehnen in consent layer to get to the PM and going there to the legitimate interest category, both interests are opted-in (so default setting is working, but Alle akzeptieren button seems to change that)

**Comment by vilasma** [comment]
closing this issue, this happened due to a change on the global vendor list (Amobee) and should have been resolved in the meanwhile.
