### ISSUE TITLE
Feature request: add ability to override the OkHttpClient()

### ISSUE THREAD

**Issue by hnljp** [SourcePointUSA/android-cmp-app#322]
**Describe the feature request**
It is at this moment not possible to override OkHttpClient().

Personally I see two issues with not being able to override the OkHttpClient()
1. It is recommended to use a single instance of the OkHttpClient() : https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html
2. We use our own custom OkHttpClient() to fix issues certificate issues, on API 21. It would be nice, to be able also to use this for this library.

**Comment by carmelo-iriti** [comment]
HI @hnljp ,

this change requires developing time, what issues is triggering your request?

**Comment by carmelo-iriti** [comment]
Since I didn’t get any answer, I'm closing this ticket
