### ISSUE TITLE
onError with Timout

### ISSUE THREAD

**Issue by gnuhel** [SourcePointUSA/android-cmp-app#327]
**Describe the bug**
Very often we experience that onError is called with a timeout exception 

** About your environment **
 - SDK version: 5.1.12
 - Device: all
 - OS: all

Why is it happening and what should we do?

**Comment by carmelo-iriti** [comment]
Hi @gnuhel ,

are you still experiencing this issue in the new V6 SDK?

**Comment by carmelo-iriti** [comment]
Since I didn’t  get any answers, I believe that this issue is not present on the V6
