### ISSUE TITLE
Multiple consent layers on top of each other

### ISSUE THREAD

**Issue by AAverin** [SourcePointUSA/android-cmp-app#330]
**Describe the bug**
It is possible to end up with multiple webviews of consent layer displayed on top of each other, resulting in the incorrect UI and tracking

**About your campaign (please complete the following information):**
settings do not matter

** About your environment **
 - SDK version - latest master
 - Device: any Android 

**To Reproduce**
1. Run sample app with web campaign
2. Tap on `Privacy policy`
3. Go back to the app
4. Repeat a few times
4. Click on X to close webview
5. Observe multiple webviews underneath

**Expected behavior**
There should be only one consent layer displayed in the app at any moment and never multiple on top of each other

Attaching a video

https://user-images.githubusercontent.com/1481332/115247088-c2905480-a126-11eb-8d6b-630095951541.mp4

**Comment by Nevazhnovu** [comment]
@AAverin since OnResume() is called by Android every time app become in focus it’s more likely a feature than a bug. 
Next code snippet is fixing this issue for exemplary app:

```java
private boolean isConsentLibRun = false;    //boolean flag which should be set to true once buildGDPRConsentLib().run() is invoked

@Override
protected void onResume() {
    super.onResume();
    if(!isConsentLibRun) {
        //we can get here only once
        isConsentLibRun = true;
        buildGDPRConsentLib().run();
    }
}
```

**Comment by AAverin** [comment]
Could you please update your sample app and documentation to mention this required "workaround" to be in the code?

**Comment by carmelo-iriti** [comment]
Hi @AAverin, thanks for your message; 
this is a known issue that we are solving with the next release planned for April 27th

**Comment by carmelo-iriti** [comment]
issue solved in v6
