### ISSUE TITLE
Progard config

### ISSUE THREAD

**Issue by joncasagrande** [SourcePointUSA/android-cmp-app#356]
Hello i will create this issue just to improve the readme

I noticed that you don't have the progard config enabled, and it would be nice to have

```
# Sourcepoint (CMP)
-keep interface com.sourcepoint.** { *; }
-keep class com.sourcepoint.** { *; }
```

**Comment by carmelo-iriti** [comment]
Hi @joncasagrande,

Thanks for the message, are you referring to the example app?

**Comment by joncasagrande** [comment]
Example app, we had an issue related to that, so i thought it would be nice to have it.

**Comment by carmelo-iriti** [comment]
Fair enough, 
ok I'll add it to our example and thanks for the contribution

**Comment by carmelo-iriti** [comment]
Hi @joncasagrande, I updated the README.md with the proguard config rules, a full working example will be ready in 3 weeks and thanks again for the contribution
