### ISSUE TITLE
Privacy manager fails to load when sharedUserId is set in the manifest

### ISSUE THREAD

**Issue by jakobulbrich** [SourcePointUSA/android-cmp-app#395]
**Describe the bug**
When an `android:sharedUserId="..."` is set in the manifest of the application the `js_receiver.js` file that is used in `ConsentWebView.loadConsentUIFromUrl()` cannot be resolved with the `file2String()` method.
Since the sharedUserId results in a different classLoader `getResourceAsStream(...)` for this file returns null and the subsequent call will therefore throw a `java.lang.NullPointerException`. The error is caught internally but the privacy manager does not show up.

```text
java.lang.NullPointerException: currentThread()
    .contextClassLoader
    .getResourceAsStream(this) must not be null
    at com.sourcepoint.cmplibrary.util.IOUtilsKt.file2String(IOUtils.kt:5)
    at com.sourcepoint.cmplibrary.core.web.ConsentWebView$loadConsentUIFromUrl$2$1.invoke(ConsentWebView.kt:112)
```

**About your environment**
 - SDK version: 6.1.1 and 6.1.2
 - Device: Emulator
 - OS: Android 11

**To Reproduce**
1. Set `android:sharedUserId="..."` in the manifest of the application
2. Initialize the spConsentLib (in my case with `CampaignType.GDPR`)
3. Call `loadPrivacyManager(pmId, PMTab.PURPOSES, CampaignType.GDPR)`
4. Privacy manager cannot be loaded due to the internal exception

**Suggestions**
Don't use the `contextClassLoader` to resolve the js file, but just put it in the assets and read it from there.

**Comment by carmelo-iriti** [comment]
Hi @jakobulbrich , 
Thanks for the detailed  message, we already added it in our queue

**Comment by carmelo-iriti** [comment]
Hey @jakobulbrich,

I've created a staging artifact with the fix and it looks working, can you please give it a try and give me a feedback?

to test it you should add in the `build.gradle` file the following repo 
```

allprojects {
    repositories {
        ...
        maven { url "https://s01.oss.sonatype.org/service/local/repositories/comsourcepoint-1040/content/"}
        ...
}
```
and then update the version to
`implementation 'com.sourcepoint.cmplibrary:cmplibrary:6.1.4'`

as soon as I'll get your feedback, I'll promote the artifact in production

**Comment by carmelo-iriti** [comment]
Hi @jakobulbrich, 

Please ignore the previous message, I just released the artifact in production

**Comment by jakobulbrich** [comment]
Hi @carmelo-iriti,
I was just about to test the staging artifact. I've now tested directly with the latest production release and can confirm that it is now working.

Thank you

**Comment by carmelo-iriti** [comment]
@jakobulbrich  thanks for the feedback! 👍🏻
