### ISSUE TITLE
Cannot call showPrivacyManager() or customConsentGDPR() without loadMessage()

### ISSUE THREAD

**Issue by jakobulbrich** [SourcePointUSA/android-cmp-app#400]
**Describe the bug**
After creating the library with `spConsentLibLazy {}` I cannot successfully call `showPrivacyManager()` and `customConsentGDPR()` anymore. Both calls fail unless I had a previous successful call to `showMessage()` on the same library instance.

**About your environment**
 - SDK version: com.sourcepoint.cmplibrary:cmplibrary:6.1.2
 - Device: Emulator
 - OS: Android 11

**To Reproduce**
1. initialize the sourcepoint library
2. Do not call `showMessage()`
3. call `showPrivacyManager()` or `customConsentGDPR()`
4. Both calls will fail

**Expected behavior**
Is this intended behavior that we need to init the library with a call to `showMessage()` and need to use the same instance also for all other calls? It is not stated in the docs and wasn't necessary in previous versions. I would expect that we can use different instances of the lib during the runtime of the app to call these methods

**Comment by carmelo-iriti** [comment]
Hi @jakobulbrich,

what you are describing is the expected behaviour.

The `showMessage` method make the library fetching the current configuration and show the message if it is necessary, without calling this method is not possible to invoke the PM because you don’t which configuration to use for it.

**Comment by jakobulbrich** [comment]
I would then recommend to
- add this behavior description to the documentation
- add proper error logs when one forgets to call `loadMessage()` before the other calls

because this behavior was totally unclear and required debugging to find out why the calls did not work.

Also how are we expected to force-show the privacy manager? Call `showMessage()` first which might already show the PM and then `loadPrivacyManager()` which will show it a second time? Since we now have to use the same Library instance and the same Client for both calls it is difficult to distinguish both things and react to the callbacks accordingly

**Comment by carmelo-iriti** [comment]
sure, we can add an explanation about the reason that the `loadMessage ` has to be called in the `onResume`.

> Also how are we expected to force-show the privacy manager? Call showMessage() first which might already show the PM and then loadPrivacyManager() which will show it a second time? Since we now have to use the same Library instance and the same Client for both calls it is difficult to distinguish both things and react to the callbacks accordingly

It sounds like something is not completely clear.

I think that the fastest way for you to get the answers to your doubts is to ask one of our account managers a 15min call, please ask also to add me in the call.
