### ISSUE TITLE
ConsentLibExceptionK subclasses marked as internal

### ISSUE THREAD

**Issue by hameno** [SourcePointUSA/android-cmp-app#403]
**Describe the bug**
Currently all ConsentLibExceptionK subclasses are marked as internal, making it impossible to handle errors in onError callback correclty depending on actual error.

**Comment by carmelo-iriti** [comment]
Hi @hameno ,

the `ConsentLibExceptionK` class wasn’t designed to be public, the exception gets sent to the client using the `Throwable`.
We call the on error callback only if the consent hasn’t been sent to our backend and that’s it.
