### ISSUE TITLE
Text flowing into/under switches in privacy manager on small devices

### ISSUE THREAD

**Issue by PhilippNowak96** [SourcePointUSA/android-cmp-app#539]
**Describe the bug**

On small devices or devices with increased text size the description text for the selectable entries in the privacy manager can flow into / under the switches (see screenshot).

** About your environment **
 - SDK version: 6.7.1
 - Device: Screenshot was taken on Samsung - Galaxy S20 FE
 - OS: Android 12 (API 31)

**To Reproduce**
1. Use a small device / emulator or increase text size on any device so description text does not fit next to the switch
2. Open privacy manager

**Expected behavior**
Text is constrained left of switch, so line break occurs earlier in our case.

**Screenshots**
![Bug5769504_IMG_02](https://user-images.githubusercontent.com/10376534/195519403-4d4b5853-224c-44b7-8232-5e95c4c53fcc.jpg)

**Additional context**

Sorry for German text in the screenshot but I guess the issue is still understandable.

**Comment by andresilveirah** [comment]
Hi @PhilippNowak96 thank you for reporting this issue. Fortunately it can be fixed via our publisher's portal with some CSS. 
Please contact your account manager and he/she will be able to help you.
