### ISSUE TITLE
PORTUGUESE typo issue in MessageLanguage enum

### ISSUE THREAD

**Issue by Joadar** [SourcePointUSA/android-cmp-app#615]
Implementing the language logic in our app, I noticed this typo issue for **PORTUGUESE** language in `MessageLanguage` enum.

https://github.com/SourcePointUSA/android-cmp-app/blob/70fed86befb08b2568639bd40894d56f32984bb9/cmplibrary/src/main/java/com/sourcepoint/cmplibrary/model/MessageLanguage.kt#L26

I was ready to open a _pull request_ but your project doesn't accept new branches from external developers.

**Comment by carmelo-iriti** [comment]
Hi @Joadar,

Thank you for the message,

Please feel free to write here the change and we'll add it in the next release

**Comment by Joadar** [comment]
**PORTUGUESE("PT")**

**Comment by carmelo-iriti** [comment]
Hi @Joadar The chance has been merged and it’ll be released today

**Comment by Joadar** [comment]
Thank you! :)
