### ISSUE TITLE
onNativeMessageReady not called at all

### ISSUE THREAD

**Issue by atiqmumtaz507** [SourcePointUSA/android-cmp-app#691]
I have an issue with the Native Message it appeared one time and after that I could not see it. I wiped the data from the emulator also uninstall the app from the device but the native message does not appear. I see only these SDK callbacks get triggered:

 - onConsentReady

 - onSpFinished

Android SDK Version used 7.3.0.
I also called SpUtils.clearAllData(getContext()); onCreate() but it does not help. Here is my config

private void buildSpConsentLib() {
        if (Configuration.USE_C1) {
            AUTH_ID = getConnector().getTrackingId();
            Timber.i("CMP AUTH_ID (C1): %s", AUTH_ID);
        } else {
            AUTH_ID = getAppInstanceGeneratedAuthId(preferences);
            Timber.i("CMP AUTH_ID (gen): %s", AUTH_ID);
        }

        SpConfig spConfig = new SpConfigDataBuilder()
                .addMessageTimeout(5000)
                .addCampaignsEnv(CampaignsEnv.STAGE)
                .addAccountId(accountId)
                .addPropertyName(propertyName)
                .addPropertyId(propertyId)
                .addMessageLanguage(MessageLanguage.GERMAN)
                .addCampaign(new SpCampaign(CampaignType.GDPR, Collections.emptyList()))
                .addCampaign(CampaignType.GDPR)
                .build();
        spConsentLib = FactoryKt.makeConsentLib(spConfig, requireActivity(), new LocalClient());
    }

onResume() I call this spConsentLib.loadMessage();

**Comment by atiqmumtaz507** [comment]
@andresilveirah

**Comment by carmelo-iriti** [comment]
Hi @atiqmumtaz507,

can you please send me your config  object with an email to carmelo@sourcepoint.com?

**Comment by atiqmumtaz507** [comment]
@carmelo-iriti Please check your Email. Thanks :-)

**Comment by carmelo-iriti** [comment]
@atiqmumtaz507 what should I look for? I didn’t receive anything from you

**Comment by atiqmumtaz507** [comment]
@carmelo-iriti I Emailed you on this address carmelo@sourcepoint.com

**Comment by atiqmumtaz507** [comment]
"From our [doc](https://github.com/SourcePointUSA/android-cmp-app#authenticated-consent) the authId is fetching an existing consent, this means that you won’t see any popup since you already accepted or reject it."

In the simulator if I reset the device and remove the data and install the app again I don't see native message. However in the old sdk version I could see a native message.

**Comment by carmelo-iriti** [comment]
Already replayed with the solution in a email

**Comment by atiqmumtaz507** [comment]
@andresilveirah I have not cleaned the code. The Auth Id generator is there unused. If I reset the device in the emulator. I should see a native message but I don't see it. You can see the config which I have sent you via Email.

**Comment by carmelo-iriti** [comment]
@atiqmumtaz507 any update?

**Comment by atiqmumtaz507** [comment]
@carmelo-iriti Can we have a call tomorrow at 13:00 O'Clock?

**Comment by carmelo-iriti** [comment]
@atiqmumtaz507 sure, can you please send me a calendar invite using carmelo@sourcepoint.com?
