### ISSUE TITLE
ConsentString is not set after onConsentReady

### ISSUE THREAD

**Issue by ibb-jile** [SourcePointUSA/android-cmp-app#87]
Hello guys , I'm not sure what is correct behavior. But _ConsentString_ and _euConsent_ are null after consent loading. I made some debugging and _euConsent_ is loaded from shared storage, but it is cleared by this line https://github.com/SourcePointUSA/android-cmp-app/blob/develop/cmplibrary/src/main/java/com/sourcepoint/gdpr_cmplibrary/GDPRConsentLib.java#L352 because _UserConsent_ does not contain _consentString_

**Comment by ibb-jile** [comment]
and ConsentString is also cleared in shared storage :-(

**Comment by leodoin** [comment]
Hey @ibb-jile, thanks for the feedback! It's not the expected behaviour, the endpoint is not actually returning the consentString as expected. So we should be able to fix it on our client side, which means, no need for another release. We have all hands on deck for solving it asap and i will ping you back as soon as the fix it deployed.

**Comment by leodoin** [comment]
Hey there, we have just released the v4.1.2 with a work around: we keep the consentString from the shared storage in case there is no change in the user consent. So one can just update the dependency to 4.1.2 and be good to go!
But we will keep this issue opened until the server side is fixed and endpoint returns the expected consentString. Thanks again for the feedback @ibb-jile !

**Comment by ibb-jile** [comment]
You are welcome :-) and thanks for quick fix!

**Comment by leodoin** [comment]
Hey guys, I'm closing this issue as both the SDK and the server no longer present any problems regarding consentString. Pls let us know if you find anything else worth noting!
